FROM tensorflow/tensorflow:2.5.0-jupyter

RUN apt-get update && apt-get install -y tesseract-ocr && apt-get clean
RUN apt-get install -y \
	libx11-6 \
	libgl1 \
	libopengl0 \
	curl

WORKDIR /usr/src/app

COPY requirements_tf2.txt ./
RUN pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_tf2.txt

COPY . .
